### ISSUE TITLE
NoMethodError on Slim.lex

### ISSUE THREAD

**Issue by DZittersteyn** [jneen/rouge#236]
When using the Slim lexer, the input string `-<<x` results in a `NoMethodError`. 

Reproducing (in `pry`):
```
> Rouge::Lexers::Slim.lex("-<<x").to_a
NoMethodError: undefined method `<<' for nil:NilClass
> wtf??
Exception: NoMethodError: undefined method `<<' for nil:NilClass
--
 0: <snip>/rouge-1.8.0/lib/rouge/lexers/ruby.rb:234:in `block (2 levels) in <class:Ruby>'
 1: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:305:in `instance_exec'
 2: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:305:in `block in step'
 3: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:287:in `each'
 4: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:287:in `step'
 5: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:290:in `block in step'
 6: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:287:in `each'
 7: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:287:in `step'
 8: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:268:in `stream_tokens'
 9: <snip>/rouge-1.8.0/lib/rouge/lexer.rb:388:in `lex'
10: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:365:in `delegate'
11: <snip>/rouge-1.8.0/lib/rouge/lexers/slim.rb:176:in `block (2 levels) in <class:Slim>'
12: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:305:in `instance_exec'
13: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:305:in `block in step'
14: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:287:in `each'
15: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:287:in `step'
16: <snip>/rouge-1.8.0/lib/rouge/regex_lexer.rb:268:in `stream_tokens'
17: <snip>/rouge-1.8.0/lib/rouge/lexer.rb:388:in `lex'
18: (pry):1:in `each'
19: (pry):1:in `to_a'
```

This issue seems to be caused by the `@heredoc_queue` not being initialized (done in the `start` block of the ruby lexer)

This issue was discovered by @danlec and reported to @Hacker0x01

**Comment by jneen** [comment]
Welp, that'd do it.  Thanks for the bug report!

**Comment by DZittersteyn** [comment]
Awesome, thanks for the fix! Any idea yet when the release with this fix will be?

**Comment by jneen** [comment]
Not sure yet, within the next week hopefully.

**Comment by jneen** [comment]
I wanna go through and make sure other lexers don't have the same problem.

**Comment by DZittersteyn** [comment]
Ah nice! Thanks again!
