### ISSUE TITLE
Crash on Ruby <2

### ISSUE THREAD

**Issue by jiphex** [jneen/rouge#589]
Rouge is required as part of Gollum which we're deploying onto Debian Wheezy hosts which come with Ruby 1.9.3.

Attempting to run Gollum in this situation raises the following traceback:

```
user@server:/etc/service/gollum# ./run
/opt/gollum/gems/gems/rouge-2.0.7/lib/rouge/lexer.rb:362:in `load': /opt/gollum/gems/gems/rouge-2.0.7/lib/rouge/lexers/abap.rb:220: syntax error, unexpected $undefined (SyntaxError)
        rule %r([-\*\+%/~=&\?<>!#@\^]+), Operator
                                  ^
/opt/gollum/gems/gems/rouge-2.0.7/lib/rouge/lexers/abap.rb:226: syntax error, unexpected $undefined
        rule %r([-\*\+%/~=&\?<>!#@\^]+), Operator
                                  ^
	from /opt/gollum/gems/gems/rouge-2.0.7/lib/rouge/lexer.rb:362:in `load_lexer'
	from /opt/gollum/gems/gems/rouge-2.0.7/lib/rouge.rb:57:in `block in <top (required)>'
	from /opt/gollum/gems/gems/rouge-2.0.7/lib/rouge.rb:56:in `each'
	from /opt/gollum/gems/gems/rouge-2.0.7/lib/rouge.rb:56:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /var/lib/gems/1.9.1/gems/gollum-lib-4.2.2/lib/gollum-lib/markup.rb:4:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /var/lib/gems/1.9.1/gems/gollum-lib-4.2.2/lib/gollum-lib.rb:32:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /var/lib/gems/1.9.1/gems/gollum-4.0.1/lib/gollum/app.rb:4:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
	from /etc/sv/gollum/config.ru:7:in `block in <main>'
	from /var/lib/gems/1.9.1/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
	from /var/lib/gems/1.9.1/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
	from /etc/sv/gollum/config.ru:in `new'
	from /etc/sv/gollum/config.ru:in `<main>'
	from /var/lib/gems/1.9.1/gems/rack-1.6.5/lib/rack/builder.rb:49:in `eval'
	from /var/lib/gems/1.9.1/gems/rack-1.6.5/lib/rack/builder.rb:49:in `new_from_string'
	from /var/lib/gems/1.9.1/gems/rack-1.6.5/lib/rack/builder.rb:40:in `parse_file'
	from /var/lib/gems/1.9.1/gems/rack-1.6.5/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /var/lib/gems/1.9.1/gems/rack-1.6.5/lib/rack/server.rb:208:in `app'
	from /var/lib/gems/1.9.1/gems/rack-1.6.5/lib/rack/server.rb:336:in `wrapped_app'
	from /var/lib/gems/1.9.1/gems/rack-1.6.5/lib/rack/server.rb:272:in `start'
	from /var/lib/gems/1.9.1/gems/rack-1.6.5/lib/rack/server.rb:147:in `start'
	from /var/lib/gems/1.9.1/gems/rack-1.6.5/bin/rackup:4:in `<top (required)>'
	from /usr/local/bin/rackup:23:in `load'
	from /usr/local/bin/rackup:23:in `<main>'
```

This can be fixed by escaping the `@` in the regex on the highlighted lines.

Fixed in #588

**Comment by katafrakt** [comment]
As this is apparently fixed (PR is merged), can the issue be closed?
