### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by brianlheim** [jneen/rouge#746]
I'm attempting to write a lexer for the [SuperCollider](https://github.com/supercollider/supercollider/) programming language.

I'm trying to run the tests as described in the readme, but I keep running into this error. Not a frequent Ruby user, fyi. Let me know if you need any more information, and thanks in advance for your help!

Environment:
OS: macOS 10.13 beta
ruby --version: 2.5.0dev (2017-06-14 trunk 59096)
bundler --version: 1.15.3

Result of `bundle install`:

```
Using rake 12.0.0
Using ast 2.3.0
Using bundler 1.15.3
Using coderay 1.1.1
Using diff-lcs 1.2.5
Using github-markup 1.6.1
Using method_source 0.8.2
Using minitest 4.7.5
Using mustermann 1.0.0
Using parallel 1.12.0
Using powerpack 0.1.1
Using predicated 0.2.6
Using slop 3.6.0
Using rack 2.0.3
Using redcarpet 3.4.0
Using rouge 2.1.1 from source at `.`
Using ruby-progressbar 1.8.1
Using unicode-display_width 1.3.0
Using sexp_processor 4.10.0
Using tilt 2.0.8
Using yard 0.9.9
Using rainbow 2.2.2
Using parser 2.4.0.0
Using pry 0.10.4
Using rack-protection 2.0.0
Using shotgun 0.9.2
Using ruby_parser 3.10.1
Using rubocop 0.49.1
Using sinatra 2.0.0
Using ruby2ruby 2.4.0
Using wrong 0.7.1
Bundle complete! 11 Gemfile dependencies, 31 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Result of `rake` (and `bundle exec rake`:

```
ruby -I./lib -r ./spec/spec_helper -r./spec/cli_spec.rb -r./spec/formatter_spec.rb -r./spec/formatters/html_linewise_spec.rb -r./spec/formatters/html_pygments_spec.rb -r./spec/formatters/html_spec.rb -r./spec/formatters/null_spec.rb -r./spec/formatters/terminal256_spec.rb -r./spec/guesser_spec.rb -r./spec/lexer_spec.rb -r./spec/lexers/abap_spec.rb -r./spec/lexers/apache_spec.rb -r./spec/lexers/apiblueprint_spec.rb -r./spec/lexers/apple_script_spec.rb -r./spec/lexers/awk_spec.rb -r./spec/lexers/biml_spec.rb -r./spec/lexers/bsl_spec.rb -r./spec/lexers/c_spec.rb -r./spec/lexers/ceylon_spec.rb -r./spec/lexers/cfscript_spec.rb -r./spec/lexers/clojure_spec.rb -r./spec/lexers/cmake_spec.rb -r./spec/lexers/coffeescript_spec.rb -r./spec/lexers/common_lisp_spec.rb -r./spec/lexers/conf_spec.rb -r./spec/lexers/coq_spec.rb -r./spec/lexers/cpp_spec.rb -r./spec/lexers/csharp_spec.rb -r./spec/lexers/css_spec.rb -r./spec/lexers/d_spec.rb -r./spec/lexers/dart_spec.rb -r./spec/lexers/diff_spec.rb -r./spec/lexers/digdag_spec.rb -r./spec/lexers/docker_spec.rb -r./spec/lexers/dot_spec.rb -r./spec/lexers/eiffel_spec.rb -r./spec/lexers/elixir_spec.rb -r./spec/lexers/erb_spec.rb -r./spec/lexers/erlang_spec.rb -r./spec/lexers/factor_spec.rb -r./spec/lexers/fortran_spec.rb -r./spec/lexers/fsharp_spec.rb -r./spec/lexers/gherkin_spec.rb -r./spec/lexers/go_spec.rb -r./spec/lexers/gradle_spec.rb -r./spec/lexers/graphql_spec.rb -r./spec/lexers/groovy_spec.rb -r./spec/lexers/haml_spec.rb -r./spec/lexers/handlebars_spec.rb -r./spec/lexers/haskell_spec.rb -r./spec/lexers/html_spec.rb -r./spec/lexers/hylang_spec.rb -r./spec/lexers/idlang_spec.rb -r./spec/lexers/igorpro_spec.rb -r./spec/lexers/ini_spec.rb -r./spec/lexers/io_spec.rb -r./spec/lexers/java_spec.rb -r./spec/lexers/javascript_spec.rb -r./spec/lexers/jinja_spec.rb -r./spec/lexers/jsonnet_spec.rb -r./spec/lexers/jsx_spec.rb -r./spec/lexers/julia_spec.rb -r./spec/lexers/kotlin_spec.rb -r./spec/lexers/lasso_spec.rb -r./spec/lexers/liquid_spec.rb -r./spec/lexers/literate_coffeescript_spec.rb -r./spec/lexers/literate_haskell_spec.rb -r./spec/lexers/llvm_spec.rb -r./spec/lexers/lua_spec.rb -r./spec/lexers/make_spec.rb -r./spec/lexers/markdown_spec.rb -r./spec/lexers/matlab_spec.rb -r./spec/lexers/moonscript_spec.rb -r./spec/lexers/mosel_spec.rb -r./spec/lexers/nginx_spec.rb -r./spec/lexers/nim_spec.rb -r./spec/lexers/nix_spec.rb -r./spec/lexers/objective_c_spec.rb -r./spec/lexers/ocaml_spec.rb -r./spec/lexers/pascal_spec.rb -r./spec/lexers/perl_spec.rb -r./spec/lexers/plain_text_spec.rb -r./spec/lexers/plist_spec.rb -r./spec/lexers/pony_spec.rb -r./spec/lexers/powershell_spec.rb -r./spec/lexers/praat_spec.rb -r./spec/lexers/prolog_spec.rb -r./spec/lexers/prometheus_spec.rb -r./spec/lexers/properties_spec.rb -r./spec/lexers/protobuf_spec.rb -r./spec/lexers/puppet_spec.rb -r./spec/lexers/python_spec.rb -r./spec/lexers/q_spec.rb -r./spec/lexers/qml_spec.rb -r./spec/lexers/r_spec.rb -r./spec/lexers/racket_spec.rb -r./spec/lexers/ruby_spec.rb -r./spec/lexers/rust_spec.rb -r./spec/lexers/scala_spec.rb -r./spec/lexers/scheme_spec.rb -r./spec/lexers/sed_spec.rb -r./spec/lexers/shell_spec.rb -r./spec/lexers/sieve_spec.rb -r./spec/lexers/slim_spec.rb -r./spec/lexers/smalltalk_spec.rb -r./spec/lexers/smarty_spec.rb -r./spec/lexers/sml_spec.rb -r./spec/lexers/sql_spec.rb -r./spec/lexers/swift_spec.rb -r./spec/lexers/tap_spec.rb -r./spec/lexers/tcl_spec.rb -r./spec/lexers/tex_spec.rb -r./spec/lexers/toml_spec.rb -r./spec/lexers/tsx_spec.rb -r./spec/lexers/tulip_spec.rb -r./spec/lexers/turtle_spec.rb -r./spec/lexers/twig_spec.rb -r./spec/lexers/typescript_spec.rb -r./spec/lexers/vala_spec.rb -r./spec/lexers/verilog_spec.rb -r./spec/lexers/viml_spec.rb -r./spec/lexers/vue_spec.rb -r./spec/lexers/wollok_spec.rb -r./spec/lexers/xml_spec.rb -r./spec/lexers/yaml_spec.rb -r./spec/lexers_spec.rb -r./spec/plugins/redcarpet_spec.rb -r./spec/theme_spec.rb -r./spec/token_spec.rb -r./spec/visual_spec.rb -e Minitest::Unit.autorun
Traceback (most recent call last):
	9: from /Users/brianheim/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	8: from /Users/brianheim/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	7: from /Users/brianheim/git/rouge/spec/spec_helper.rb:5:in `<top (required)>'
	6: from /Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler.rb:108:in `require'
	5: from /Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `require'
	4: from /Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `each'
	3: from /Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `block in require'
	2: from /Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `each'
	1: from /Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'wrong'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Wrong::Date
Backtrace for gem load error is:
/Users/brianheim/.rvm/gems/ruby-head/gems/wrong-0.7.1/lib/wrong/close_to.rb:12:in `<module:Wrong>'
/Users/brianheim/.rvm/gems/ruby-head/gems/wrong-0.7.1/lib/wrong/close_to.rb:1:in `<top (required)>'
/Users/brianheim/.rvm/gems/ruby-head/gems/wrong-0.7.1/lib/wrong/helpers.rb:5:in `require'
/Users/brianheim/.rvm/gems/ruby-head/gems/wrong-0.7.1/lib/wrong/helpers.rb:5:in `<top (required)>'
/Users/brianheim/.rvm/gems/ruby-head/gems/wrong-0.7.1/lib/wrong.rb:6:in `require'
/Users/brianheim/.rvm/gems/ruby-head/gems/wrong-0.7.1/lib/wrong.rb:6:in `<top (required)>'
/Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `require'
/Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `each'
/Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `block in require'
/Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `each'
/Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `require'
/Users/brianheim/.rvm/gems/ruby-head/gems/bundler-1.15.3/lib/bundler.rb:108:in `require'
/Users/brianheim/git/rouge/spec/spec_helper.rb:5:in `<top (required)>'
/Users/brianheim/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/brianheim/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Bundler Error Backtrace:
rake aborted!
Command failed with status (1): [ruby -I./lib -r ./spec/spec_helper -r./spe...]
/Users/brianheim/git/rouge/Rakefile:7:in `block in <top (required)>'
/Users/brianheim/.rvm/gems/ruby-head@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/brianheim/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
/Users/brianheim/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => spec
(See full trace by running task with --trace)
```

**Comment by brianlheim** [comment]
@gfx, thanks for the tip! tests pass on 2.4.0.
